services:
  backend:
    build: 
      context: ./DOON_Heritage_Backend
      dockerfile: Dockerfile.prod
    container_name: doon_backend_prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  frontend:
    build:
      context: ./DOON_Heritage_school_Frontend
      dockerfile: Dockerfile.prod
    container_name: doon_frontend_prod
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
