# Generated by Django 6.0.3 on 2026-03-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_student_roll_number_alter_student_email'),
        ('Subject_Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectteacherprofile',
            name='classes',
            field=models.ManyToManyField(related_name='subject_teachers', to='Student.classroom'),
        ),
    ]
