# Generated by Django 6.0.3 on 2026-05-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subject_Teacher', '0002_subjectteacherprofile_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectteacherprofile',
            name='classes',
        ),
    ]
