# Generated by Django 6.0.2 on 2026-03-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_student_roll_number_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='Student.subject'),
        ),
    ]
